# Generated by Django 2.2.7 on 2019-11-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=400, verbose_name='Blog Title')),
                ('blog_content', models.TextField(verbose_name='Blog Content')),
                ('blog_published', models.DateField(verbose_name='Published Date')),
            ],
        ),
    ]
